import type pg from "pg";
import { db } from "../../db/pool.ts";
import type { StoredRecord } from "../canonical/record.ts";
import type { CorpusAnalysis } from "../analysis/coverage.ts";
import type { SnapshotManifest } from "../snapshot/store.ts";

/**
 * Where adapted records live: the `corpus` schema in Postgres (see db/migrations/001_corpus.sql).
 *
 * A run is loaded in one transaction — the run, its datasets, its taxa and its records — so a
 * failed load leaves nothing half-written. Records are keyed on `source:sourceRecordId`, so
 * re-harvesting a window updates rows in place and the newest run wins; earlier runs remain
 * recoverable from their frozen snapshots.
 *
 * The mapping trace is not stored. Adapting is deterministic and the raw page is frozen, so the
 * trace for any record is regenerated by re-adapting the page it came from.
 */
export interface RecordStore {
  save(manifest: SnapshotManifest, records: StoredRecord[], analysis: CorpusAnalysis): Promise<void>;
  loadAnalysis(harvestKey: string, runId: string): Promise<CorpusAnalysis>;
}

/** Rows per INSERT. Sent as one JSON array and unpacked server-side by jsonb_to_recordset. */
const BATCH_SIZE = 2_000;

/** Column list shared by the JSON rows and the INSERT, so the two cannot drift apart. */
const OCCURRENCE_COLUMNS = [
  ["record_id", "text"],
  ["source", "text"],
  ["source_record_id", "text"],
  ["occurrence_id", "text"],
  ["harvest_id", "text"],
  ["snapshot_page", "text"],
  ["fetched_at", "timestamptz"],
  ["data_resource_uid", "text"],
  ["license", "text"],
  ["taxon_concept_id", "text"],
  ["scientific_name", "text"],
  ["vernacular_name", "text"],
  ["national_status", "text"],
  ["event_date", "timestamptz"],
  ["first_loaded_at", "timestamptz"],
  ["decimal_latitude", "double precision"],
  ["decimal_longitude", "double precision"],
  ["coordinate_uncertainty_m", "double precision"],
  ["state_province", "text"],
  ["ibra_region", "text"],
  ["locality", "text"],
  ["basis_of_record", "text"],
  ["individual_count", "integer"],
  ["recorded_by_pseudonym", "text"],
  ["occurrence_remarks", "text"],
  ["event_remarks", "text"],
  ["source_assertions", "text[]"],
  ["is_valid", "boolean"],
  ["issue_count", "integer"],
] as const;

function occurrenceRow({ record: r, issueCount }: StoredRecord): Record<string, unknown> {
  const p = r.provenance;
  return {
    record_id: r.recordId,
    source: p.source,
    source_record_id: p.sourceRecordId,
    occurrence_id: p.occurrenceId,
    harvest_id: p.harvestId,
    snapshot_page: p.snapshotPage,
    fetched_at: p.fetchedAt,
    data_resource_uid: p.dataResourceUid,
    license: p.license,
    taxon_concept_id: r.taxonConceptId,
    scientific_name: r.scientificName,
    vernacular_name: r.vernacularName,
    national_status: r.nationalStatus,
    event_date: r.eventDate,
    first_loaded_at: r.firstLoadedAt,
    decimal_latitude: r.decimalLatitude,
    decimal_longitude: r.decimalLongitude,
    coordinate_uncertainty_m: r.coordinateUncertaintyInMeters,
    state_province: r.stateProvince,
    ibra_region: r.ibraRegion,
    locality: r.locality,
    basis_of_record: r.basisOfRecord,
    individual_count: r.individualCount,
    recorded_by_pseudonym: r.recordedByPseudonym,
    occurrence_remarks: r.occurrenceRemarks,
    event_remarks: r.eventRemarks,
    source_assertions: r.sourceAssertions,
    is_valid: r.isValid,
    issue_count: issueCount,
  };
}

const columnNames = OCCURRENCE_COLUMNS.map(([name]) => name);
const INSERT_OCCURRENCES = `
  insert into corpus.occurrences (${columnNames.join(", ")})
  select ${columnNames.join(", ")}
  from jsonb_to_recordset($1::jsonb) as x(${OCCURRENCE_COLUMNS.map(([n, t]) => `${n} ${t}`).join(", ")})
  on conflict (record_id) do update set
    ${columnNames.filter((n) => n !== "record_id").map((n) => `${n} = excluded.${n}`).join(",\n    ")}`;

async function saveRun(client: pg.PoolClient, m: SnapshotManifest, analysis: CorpusAnalysis): Promise<string> {
  const harvestId = `${m.harvestKey}/${m.runId}`;
  await client.query(
    `insert into corpus.harvest_runs
       (harvest_id, harvest_key, run_id, source, description, query, started_at, finished_at,
        expected_records, retrieved_records, complete, corpus_hash, request_count, warnings, analysis)
     values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
     on conflict (harvest_id) do update set analysis = excluded.analysis, loaded_at = now()`,
    [
      harvestId, m.harvestKey, m.runId, m.source, m.description, JSON.stringify(m.query),
      m.startedAt, m.finishedAt, m.expectedRecords, m.retrievedRecords, m.complete,
      m.corpusHash, m.requestCount, JSON.stringify(m.warnings), JSON.stringify(analysis),
    ],
  );
  return harvestId;
}

/** New datasets arrive as 'wild'; a curated kind and an existing name are never overwritten. */
async function saveDatasets(client: pg.PoolClient, records: StoredRecord[]): Promise<void> {
  const datasets = new Map<string, string | null>();
  for (const { record } of records) {
    const uid = record.provenance.dataResourceUid;
    if (uid && !datasets.has(uid)) datasets.set(uid, record.provenance.dataResourceName);
  }
  if (datasets.size === 0) return;
  await client.query(
    `insert into corpus.datasets (data_resource_uid, name)
     select uid, name from unnest($1::text[], $2::text[]) as x(uid, name)
     on conflict (data_resource_uid) do update
       set name = coalesce(corpus.datasets.name, excluded.name)`,
    [[...datasets.keys()], [...datasets.values()]],
  );
}

/** Taxa take the values from this run, including the national status ALA attached to them. */
async function saveTaxa(client: pg.PoolClient, records: StoredRecord[], seenAt: string): Promise<void> {
  const taxa = new Map<string, Record<string, unknown>>();
  for (const { record: r } of records) {
    if (!r.taxonConceptId || taxa.has(r.taxonConceptId)) continue;
    taxa.set(r.taxonConceptId, {
      taxon_concept_id: r.taxonConceptId,
      scientific_name: r.scientificName,
      vernacular_name: r.vernacularName,
      taxon_rank: r.taxonRank,
      kingdom: r.kingdom,
      phylum: r.phylum,
      taxon_class: r.taxonClass,
      taxon_order: r.order,
      family: r.family,
      genus: r.genus,
      national_status: r.nationalStatus,
    });
  }
  if (taxa.size === 0) return;
  await client.query(
    `insert into corpus.taxa (taxon_concept_id, scientific_name, vernacular_name, taxon_rank, kingdom,
                              phylum, taxon_class, taxon_order, family, genus, national_status, status_seen_at)
     select x.*, $2::timestamptz from jsonb_to_recordset($1::jsonb) as x(
       taxon_concept_id text, scientific_name text, vernacular_name text, taxon_rank text, kingdom text,
       phylum text, taxon_class text, taxon_order text, family text, genus text, national_status text)
     on conflict (taxon_concept_id) do update set
       scientific_name = excluded.scientific_name, vernacular_name = excluded.vernacular_name,
       taxon_rank = excluded.taxon_rank, kingdom = excluded.kingdom, phylum = excluded.phylum,
       taxon_class = excluded.taxon_class, taxon_order = excluded.taxon_order, family = excluded.family,
       genus = excluded.genus, national_status = excluded.national_status,
       status_seen_at = excluded.status_seen_at
     where excluded.status_seen_at >= corpus.taxa.status_seen_at`,
    [JSON.stringify([...taxa.values()]), seenAt],
  );
}

export class PostgresRecordStore implements RecordStore {
  async save(manifest: SnapshotManifest, records: StoredRecord[], analysis: CorpusAnalysis): Promise<void> {
    const client = await db().connect();
    try {
      await client.query("begin");
      await saveRun(client, manifest, analysis);
      await saveDatasets(client, records);
      await saveTaxa(client, records, manifest.finishedAt);
      for (let i = 0; i < records.length; i += BATCH_SIZE) {
        const batch = records.slice(i, i + BATCH_SIZE).map(occurrenceRow);
        await client.query(INSERT_OCCURRENCES, [JSON.stringify(batch)]);
      }
      await client.query("commit");
    } catch (error) {
      await client.query("rollback");
      throw error;
    } finally {
      client.release();
    }
  }

  async loadAnalysis(harvestKey: string, runId: string): Promise<CorpusAnalysis> {
    const { rows } = await db().query<{ analysis: CorpusAnalysis | null }>(
      "select analysis from corpus.harvest_runs where harvest_id = $1",
      [`${harvestKey}/${runId}`],
    );
    if (!rows[0]?.analysis) {
      throw new Error(`no loaded run ${harvestKey}/${runId} — run: npm run ingest -- adapt ${harvestKey} ${runId}`);
    }
    return rows[0].analysis;
  }
}

export const recordStore: RecordStore = new PostgresRecordStore();
